[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/dtla"
  to = "/dtla.html"
  status = 200

[[redirects]]
  from = "/laveen"
  to = "/laveen.html"
  status = 200
