[build]
  publish = "dist"
  command = "node build.js"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/dtla"
  to = "/dtla.html"
  status = 200
  force = true

[[redirects]]
  from = "/laveen"
  to = "/laveen.html"
  status = 200
  force = true

[[redirects]]
  from = "/lalife"
  to = "/lalife.html"
  status = 200
  force = true

[[redirects]]
  from = "/desertlife"
  to = "/desertlife.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200
  force = true
